In [3]:
import tensorflow as tf
import numpy as np
np.set_printoptions(precision=3)

a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [4]:
print(t_b)

tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [5]:
t_ones = tf.ones((2, 3))
t_ones.shape

TensorShape([2, 3])

In [6]:
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [7]:
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)

In [8]:
print(const_tensor)

tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)
