## 텐서플로에서 텐서 만들기

In [1]:
import tensorflow as tf
import numpy as np
np.set_printoptions(precision=3)

a = np.array([1, 2, 3], dtype=np.int32) # shape (3,)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [2]:
t_ones = tf.ones((2, 3))
t_ones.shape

TensorShape([2, 3])

In [3]:
# 텐서가 참조하는 값 얻기
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [4]:
# 상수 값을 가진 텐서 만들기
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print(const_tensor)

tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)


## 텐서의 데이터 타입과 크기 조작
모델이나 연산에 맞는 입력을 준비하려면 텐서를 조작하는 법을 알아야 한다.
- cast
- reshape
- transpose
- squeeze

In [5]:
# cast: 텐서의 데이터 타입을 원하는 타입으로 바꿈
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)

<dtype: 'int64'>


In [7]:
# 텐서의 크기를 바꾸고 차원을 추가하거나 불필요한 차원을 제거
# 텐서 전치하기
t = tf.random.uniform(shape=(3, 5))
t_tr = tf.transpose(t)
print(t.shape, '-->', t_tr.shape)

# 텐서 크기 바꾸기
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape=(5, 6))
print(t_reshape.shape)

# 불필요한 차원 삭제하기
t = tf.zeros((1, 2, 1, 4, 1))
t_sqz = tf.squeeze(t, axis=(2, 4))
print(t.shape, '-->', t_sqz.shape)

(3, 5) --> (5, 3)
(5, 6)
(1, 2, 1, 4, 1) --> (1, 2, 4)


## 텐서에 수학 연산 적용
- 원소별 곱셈
- 행렬 곱셈
- 텐서의 노름 연산

In [8]:
tf.random.set_seed(1)
# [-1, 1) 사이의 균등 분포
t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)
# 표준 정규 분포
t2 = tf.random.normal(shape=(5, 2), mean=0.0, stddev=1.0)
print('t1:', t1)
print('t2:', t2)
# 원소별 곱셈
t3 = tf.multiply(t1, t2).numpy()
print(t3)

t1: tf.Tensor(
[[-0.67   0.803]
 [ 0.262 -0.131]
 [-0.416  0.285]
 [ 0.952 -0.13 ]
 [ 0.32   0.21 ]], shape=(5, 2), dtype=float32)
t2: tf.Tensor(
[[ 0.403 -1.088]
 [-0.063  1.337]
 [ 0.712 -0.489]
 [-0.764 -1.037]
 [-1.252  0.021]], shape=(5, 2), dtype=float32)
[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


In [9]:
# 각 열의 평균 계산
t4 = tf.math.reduce_mean(t1, axis=0)
print(t4)

tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)


In [13]:
# 행렬 곱셈
t5 = tf.linalg.matmul(t1, t2, transpose_b=True) # t2 전치
print('t5: \n', t5.numpy())

t6 = tf.linalg.matmul(t1, t2, transpose_a=True) # t1 전치
print('t6: \n', t6.numpy())

t5: 
 [[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]]
t6: 
 [[-1.711  0.302]
 [ 0.371 -1.049]]


In [14]:
# 텐서의 노름 계산
norm_t1 = tf.norm(t1, ord=2, axis=1).numpy() # L2 노름
print(norm_t1)

[1.046 0.293 0.504 0.96  0.383]


## split(), stack(), concat() 함수
하나의 텐서를 여러개의 텐서로 나누거나 여러개의 텐서를 쌓거나, 연결하여 하나의 텐서로 만드는 연산